🔨 Add concurrency control to prevent duplicate release tag errors Queues workflow runs instead of allowing concurrent executions that would attempt to create the same release tag.
```yaml
group: ${{ github.workflow }}-${{ github.ref }}
```
should resolve to:
```
Build and Push-refs/heads/main
```

https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency solves our build tag overlap issue when we push too much code at once
i.e. https://github.com/icefoganalytics/wrap/actions/runs/18763954368/job/53534969197
> Error: Error 422: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"} - https://docs.github.com/rest/releases/releases#create-a-release

See https://github.com/icefoganalytics/wrap/commit/139d24da1567990142613b5f1a8d2f648fd628a5